export function getIconList() {
  let iconList = []

iconList.push("ri-home-line");
iconList.push("ri-home-fill");
iconList.push("ri-home-2-line");
iconList.push("ri-home-2-fill");
iconList.push("ri-home-3-line");
iconList.push("ri-home-3-fill");
iconList.push("ri-home-4-line");
iconList.push("ri-home-4-fill");
iconList.push("ri-home-5-line");
iconList.push("ri-home-5-fill");
iconList.push("ri-home-6-line");
iconList.push("ri-home-6-fill");
iconList.push("ri-home-7-line");
iconList.push("ri-home-7-fill");
iconList.push("ri-home-8-line");
iconList.push("ri-home-8-fill");
iconList.push("ri-home-gear-line");
iconList.push("ri-home-gear-fill");
iconList.push("ri-home-wifi-line");
iconList.push("ri-home-wifi-fill");
iconList.push("ri-home-smile-line");
iconList.push("ri-home-smile-fill");
iconList.push("ri-home-smile-2-line");
iconList.push("ri-home-smile-2-fill");
iconList.push("ri-home-heart-line");
iconList.push("ri-home-heart-fill");
iconList.push("ri-building-line");
iconList.push("ri-building-fill");
iconList.push("ri-building-2-line");
iconList.push("ri-building-2-fill");
iconList.push("ri-building-3-line");
iconList.push("ri-building-3-fill");
iconList.push("ri-building-4-line");
iconList.push("ri-building-4-fill");
iconList.push("ri-hotel-line");
iconList.push("ri-hotel-fill");
iconList.push("ri-community-line");
iconList.push("ri-community-fill");
iconList.push("ri-government-line");
iconList.push("ri-government-fill");
iconList.push("ri-bank-line");
iconList.push("ri-bank-fill");
iconList.push("ri-store-line");
iconList.push("ri-store-fill");
iconList.push("ri-store-2-line");
iconList.push("ri-store-2-fill");
iconList.push("ri-store-3-line");
iconList.push("ri-store-3-fill");
iconList.push("ri-hospital-line");
iconList.push("ri-hospital-fill");
iconList.push("ri-ancient-gate-line");
iconList.push("ri-ancient-gate-fill");
iconList.push("ri-ancient-pavilion-line");
iconList.push("ri-ancient-pavilion-fill");
iconList.push("ri-mail-line");
iconList.push("ri-mail-fill");
iconList.push("ri-mail-open-line");
iconList.push("ri-mail-open-fill");
iconList.push("ri-mail-send-line");
iconList.push("ri-mail-send-fill");
iconList.push("ri-mail-unread-line");
iconList.push("ri-mail-unread-fill");
iconList.push("ri-mail-add-line");
iconList.push("ri-mail-add-fill");
iconList.push("ri-mail-check-line");
iconList.push("ri-mail-check-fill");
iconList.push("ri-mail-close-line");
iconList.push("ri-mail-close-fill");
iconList.push("ri-mail-download-line");
iconList.push("ri-mail-download-fill");
iconList.push("ri-mail-forbid-line");
iconList.push("ri-mail-forbid-fill");
iconList.push("ri-mail-lock-line");
iconList.push("ri-mail-lock-fill");
iconList.push("ri-mail-settings-line");
iconList.push("ri-mail-settings-fill");
iconList.push("ri-mail-star-line");
iconList.push("ri-mail-star-fill");
iconList.push("ri-mail-volume-line");
iconList.push("ri-mail-volume-fill");
iconList.push("ri-inbox-line");
iconList.push("ri-inbox-fill");
iconList.push("ri-inbox-archive-line");
iconList.push("ri-inbox-archive-fill");
iconList.push("ri-inbox-unarchive-line");
iconList.push("ri-inbox-unarchive-fill");
iconList.push("ri-cloud-line");
iconList.push("ri-cloud-fill");
iconList.push("ri-cloud-off-line");
iconList.push("ri-cloud-off-fill");
iconList.push("ri-attachment-line");
iconList.push("ri-attachment-fill");
iconList.push("ri-profile-line");
iconList.push("ri-profile-fill");
iconList.push("ri-archive-line");
iconList.push("ri-archive-fill");
iconList.push("ri-archive-drawer-line");
iconList.push("ri-archive-drawer-fill");
iconList.push("ri-at-line");
iconList.push("ri-at-fill");
iconList.push("ri-award-line");
iconList.push("ri-award-fill");
iconList.push("ri-medal-line");
iconList.push("ri-medal-fill");
iconList.push("ri-medal-2-line");
iconList.push("ri-medal-2-fill");
iconList.push("ri-bar-chart-line");
iconList.push("ri-bar-chart-fill");
iconList.push("ri-bar-chart-horizontal-line");
iconList.push("ri-bar-chart-horizontal-fill");
iconList.push("ri-bar-chart-2-line");
iconList.push("ri-bar-chart-2-fill");
iconList.push("ri-bar-chart-box-line");
iconList.push("ri-bar-chart-box-fill");
iconList.push("ri-bar-chart-grouped-line");
iconList.push("ri-bar-chart-grouped-fill");
iconList.push("ri-bubble-chart-line");
iconList.push("ri-bubble-chart-fill");
iconList.push("ri-pie-chart-line");
iconList.push("ri-pie-chart-fill");
iconList.push("ri-pie-chart-2-line");
iconList.push("ri-pie-chart-2-fill");
iconList.push("ri-pie-chart-box-line");
iconList.push("ri-pie-chart-box-fill");
iconList.push("ri-donut-chart-line");
iconList.push("ri-donut-chart-fill");
iconList.push("ri-line-chart-line");
iconList.push("ri-line-chart-fill");
iconList.push("ri-bookmark-line");
iconList.push("ri-bookmark-fill");
iconList.push("ri-bookmark-2-line");
iconList.push("ri-bookmark-2-fill");
iconList.push("ri-bookmark-3-line");
iconList.push("ri-bookmark-3-fill");
iconList.push("ri-briefcase-line");
iconList.push("ri-briefcase-fill");
iconList.push("ri-briefcase-2-line");
iconList.push("ri-briefcase-2-fill");
iconList.push("ri-briefcase-3-line");
iconList.push("ri-briefcase-3-fill");
iconList.push("ri-briefcase-4-line");
iconList.push("ri-briefcase-4-fill");
iconList.push("ri-briefcase-5-line");
iconList.push("ri-briefcase-5-fill");
iconList.push("ri-calculator-line");
iconList.push("ri-calculator-fill");
iconList.push("ri-calendar-line");
iconList.push("ri-calendar-fill");
iconList.push("ri-calendar-2-line");
iconList.push("ri-calendar-2-fill");
iconList.push("ri-calendar-event-line");
iconList.push("ri-calendar-event-fill");
iconList.push("ri-calendar-todo-line");
iconList.push("ri-calendar-todo-fill");
iconList.push("ri-calendar-check-line");
iconList.push("ri-calendar-check-fill");
iconList.push("ri-customer-service-line");
iconList.push("ri-customer-service-fill");
iconList.push("ri-customer-service-2-line");
iconList.push("ri-customer-service-2-fill");
iconList.push("ri-flag-line");
iconList.push("ri-flag-fill");
iconList.push("ri-flag-2-line");
iconList.push("ri-flag-2-fill");
iconList.push("ri-global-line");
iconList.push("ri-global-fill");
iconList.push("ri-honour-line");
iconList.push("ri-honour-fill");
iconList.push("ri-links-line");
iconList.push("ri-links-fill");
iconList.push("ri-printer-line");
iconList.push("ri-printer-fill");
iconList.push("ri-printer-cloud-line");
iconList.push("ri-printer-cloud-fill");
iconList.push("ri-record-mail-line");
iconList.push("ri-record-mail-fill");
iconList.push("ri-reply-line");
iconList.push("ri-reply-fill");
iconList.push("ri-reply-all-line");
iconList.push("ri-reply-all-fill");
iconList.push("ri-send-plane-line");
iconList.push("ri-send-plane-fill");
iconList.push("ri-send-plane-2-line");
iconList.push("ri-send-plane-2-fill");
iconList.push("ri-projector-line");
iconList.push("ri-projector-fill");
iconList.push("ri-projector-2-line");
iconList.push("ri-projector-2-fill");
iconList.push("ri-slideshow-line");
iconList.push("ri-slideshow-fill");
iconList.push("ri-slideshow-2-line");
iconList.push("ri-slideshow-2-fill");
iconList.push("ri-slideshow-3-line");
iconList.push("ri-slideshow-3-fill");
iconList.push("ri-slideshow-4-line");
iconList.push("ri-slideshow-4-fill");
iconList.push("ri-window-line");
iconList.push("ri-window-fill");
iconList.push("ri-window-2-line");
iconList.push("ri-window-2-fill");
iconList.push("ri-stack-line");
iconList.push("ri-stack-fill");
iconList.push("ri-service-line");
iconList.push("ri-service-fill");
iconList.push("ri-registered-line");
iconList.push("ri-registered-fill");
iconList.push("ri-trademark-line");
iconList.push("ri-trademark-fill");
iconList.push("ri-advertisement-line");
iconList.push("ri-advertisement-fill");
iconList.push("ri-copyleft-line");
iconList.push("ri-copyleft-fill");
iconList.push("ri-copyright-line");
iconList.push("ri-copyright-fill");
iconList.push("ri-creative-commons-line");
iconList.push("ri-creative-commons-fill");
iconList.push("ri-creative-commons-by-line");
iconList.push("ri-creative-commons-by-fill");
iconList.push("ri-creative-commons-nc-line");
iconList.push("ri-creative-commons-nc-fill");
iconList.push("ri-creative-commons-nd-line");
iconList.push("ri-creative-commons-nd-fill");
iconList.push("ri-creative-commons-sa-line");
iconList.push("ri-creative-commons-sa-fill");
iconList.push("ri-creative-commons-zero-line");
iconList.push("ri-creative-commons-zero-fill");
iconList.push("ri-chat-1-line");
iconList.push("ri-chat-1-fill");
iconList.push("ri-chat-2-line");
iconList.push("ri-chat-2-fill");
iconList.push("ri-chat-3-line");
iconList.push("ri-chat-3-fill");
iconList.push("ri-chat-4-line");
iconList.push("ri-chat-4-fill");
iconList.push("ri-message-line");
iconList.push("ri-message-fill");
iconList.push("ri-message-2-line");
iconList.push("ri-message-2-fill");
iconList.push("ri-message-3-line");
iconList.push("ri-message-3-fill");
iconList.push("ri-chat-check-line");
iconList.push("ri-chat-check-fill");
iconList.push("ri-chat-delete-line");
iconList.push("ri-chat-delete-fill");
iconList.push("ri-chat-forward-line");
iconList.push("ri-chat-forward-fill");
iconList.push("ri-chat-upload-line");
iconList.push("ri-chat-upload-fill");
iconList.push("ri-chat-download-line");
iconList.push("ri-chat-download-fill");
iconList.push("ri-chat-new-line");
iconList.push("ri-chat-new-fill");
iconList.push("ri-chat-settings-line");
iconList.push("ri-chat-settings-fill");
iconList.push("ri-chat-smile-line");
iconList.push("ri-chat-smile-fill");
iconList.push("ri-chat-smile-2-line");
iconList.push("ri-chat-smile-2-fill");
iconList.push("ri-chat-smile-3-line");
iconList.push("ri-chat-smile-3-fill");
iconList.push("ri-chat-heart-line");
iconList.push("ri-chat-heart-fill");
iconList.push("ri-chat-off-line");
iconList.push("ri-chat-off-fill");
iconList.push("ri-feedback-line");
iconList.push("ri-feedback-fill");
iconList.push("ri-discuss-line");
iconList.push("ri-discuss-fill");
iconList.push("ri-question-answer-line");
iconList.push("ri-question-answer-fill");
iconList.push("ri-questionnaire-line");
iconList.push("ri-questionnaire-fill");
iconList.push("ri-video-chat-line");
iconList.push("ri-video-chat-fill");
iconList.push("ri-chat-voice-line");
iconList.push("ri-chat-voice-fill");
iconList.push("ri-chat-quote-line");
iconList.push("ri-chat-quote-fill");
iconList.push("ri-chat-follow-up-line");
iconList.push("ri-chat-follow-up-fill");
iconList.push("ri-chat-poll-line");
iconList.push("ri-chat-poll-fill");
iconList.push("ri-chat-history-line");
iconList.push("ri-chat-history-fill");
iconList.push("ri-chat-private-line");
iconList.push("ri-chat-private-fill");
iconList.push("ri-pencil-line");
iconList.push("ri-pencil-fill");
iconList.push("ri-edit-line");
iconList.push("ri-edit-fill");
iconList.push("ri-edit-2-line");
iconList.push("ri-edit-2-fill");
iconList.push("ri-ball-pen-line");
iconList.push("ri-ball-pen-fill");
iconList.push("ri-quill-pen-line");
iconList.push("ri-quill-pen-fill");
iconList.push("ri-pen-nib-line");
iconList.push("ri-pen-nib-fill");
iconList.push("ri-ink-bottle-line");
iconList.push("ri-ink-bottle-fill");
iconList.push("ri-mark-pen-line");
iconList.push("ri-mark-pen-fill");
iconList.push("ri-markup-line");
iconList.push("ri-markup-fill");
iconList.push("ri-edit-box-line");
iconList.push("ri-edit-box-fill");
iconList.push("ri-edit-circle-line");
iconList.push("ri-edit-circle-fill");
iconList.push("ri-sip-line");
iconList.push("ri-sip-fill");
iconList.push("ri-brush-line");
iconList.push("ri-brush-fill");
iconList.push("ri-brush-2-line");
iconList.push("ri-brush-2-fill");
iconList.push("ri-brush-3-line");
iconList.push("ri-brush-3-fill");
iconList.push("ri-brush-4-line");
iconList.push("ri-brush-4-fill");
iconList.push("ri-paint-brush-line");
iconList.push("ri-paint-brush-fill");
iconList.push("ri-contrast-line");
iconList.push("ri-contrast-fill");
iconList.push("ri-contrast-2-line");
iconList.push("ri-contrast-2-fill");
iconList.push("ri-drop-line");
iconList.push("ri-drop-fill");
iconList.push("ri-blur-off-line");
iconList.push("ri-blur-off-fill");
iconList.push("ri-contrast-drop-line");
iconList.push("ri-contrast-drop-fill");
iconList.push("ri-contrast-drop-2-line");
iconList.push("ri-contrast-drop-2-fill");
iconList.push("ri-compasses-line");
iconList.push("ri-compasses-fill");
iconList.push("ri-compasses-2-line");
iconList.push("ri-compasses-2-fill");
iconList.push("ri-scissors-line");
iconList.push("ri-scissors-fill");
iconList.push("ri-scissors-cut-line");
iconList.push("ri-scissors-cut-fill");
iconList.push("ri-scissors-2-line");
iconList.push("ri-scissors-2-fill");
iconList.push("ri-slice-line");
iconList.push("ri-slice-fill");
iconList.push("ri-eraser-line");
iconList.push("ri-eraser-fill");
iconList.push("ri-ruler-line");
iconList.push("ri-ruler-fill");
iconList.push("ri-ruler-2-line");
iconList.push("ri-ruler-2-fill");
iconList.push("ri-pencil-ruler-line");
iconList.push("ri-pencil-ruler-fill");
iconList.push("ri-pencil-ruler-2-line");
iconList.push("ri-pencil-ruler-2-fill");
iconList.push("ri-t-box-line");
iconList.push("ri-t-box-fill");
iconList.push("ri-input-method-line");
iconList.push("ri-input-method-fill");
iconList.push("ri-artboard-line");
iconList.push("ri-artboard-fill");
iconList.push("ri-artboard-2-line");
iconList.push("ri-artboard-2-fill");
iconList.push("ri-crop-line");
iconList.push("ri-crop-fill");
iconList.push("ri-crop-2-line");
iconList.push("ri-crop-2-fill");
iconList.push("ri-screenshot-line");
iconList.push("ri-screenshot-fill");
iconList.push("ri-screenshot-2-line");
iconList.push("ri-screenshot-2-fill");
iconList.push("ri-drag-move-line");
iconList.push("ri-drag-move-fill");
iconList.push("ri-drag-move-2-line");
iconList.push("ri-drag-move-2-fill");
iconList.push("ri-focus-line");
iconList.push("ri-focus-fill");
iconList.push("ri-focus-2-line");
iconList.push("ri-focus-2-fill");
iconList.push("ri-focus-3-line");
iconList.push("ri-focus-3-fill");
iconList.push("ri-paint-line");
iconList.push("ri-paint-fill");
iconList.push("ri-palette-line");
iconList.push("ri-palette-fill");
iconList.push("ri-pantone-line");
iconList.push("ri-pantone-fill");
iconList.push("ri-shape-line");
iconList.push("ri-shape-fill");
iconList.push("ri-shape-2-line");
iconList.push("ri-shape-2-fill");
iconList.push("ri-magic-line");
iconList.push("ri-magic-fill");
iconList.push("ri-anticlockwise-line");
iconList.push("ri-anticlockwise-fill");
iconList.push("ri-anticlockwise-2-line");
iconList.push("ri-anticlockwise-2-fill");
iconList.push("ri-clockwise-line");
iconList.push("ri-clockwise-fill");
iconList.push("ri-clockwise-2-line");
iconList.push("ri-clockwise-2-fill");
iconList.push("ri-hammer-line");
iconList.push("ri-hammer-fill");
iconList.push("ri-tools-line");
iconList.push("ri-tools-fill");
iconList.push("ri-drag-drop-line");
iconList.push("ri-drag-drop-fill");
iconList.push("ri-table-line");
iconList.push("ri-table-fill");
iconList.push("ri-table-alt-line");
iconList.push("ri-table-alt-fill");
iconList.push("ri-layout-line");
iconList.push("ri-layout-fill");
iconList.push("ri-layout-2-line");
iconList.push("ri-layout-2-fill");
iconList.push("ri-layout-3-line");
iconList.push("ri-layout-3-fill");
iconList.push("ri-layout-4-line");
iconList.push("ri-layout-4-fill");
iconList.push("ri-layout-5-line");
iconList.push("ri-layout-5-fill");
iconList.push("ri-layout-6-line");
iconList.push("ri-layout-6-fill");
iconList.push("ri-layout-column-line");
iconList.push("ri-layout-column-fill");
iconList.push("ri-layout-row-line");
iconList.push("ri-layout-row-fill");
iconList.push("ri-layout-top-line");
iconList.push("ri-layout-top-fill");
iconList.push("ri-layout-right-line");
iconList.push("ri-layout-right-fill");
iconList.push("ri-layout-bottom-line");
iconList.push("ri-layout-bottom-fill");
iconList.push("ri-layout-left-line");
iconList.push("ri-layout-left-fill");
iconList.push("ri-layout-top-2-line");
iconList.push("ri-layout-top-2-fill");
iconList.push("ri-layout-right-2-line");
iconList.push("ri-layout-right-2-fill");
iconList.push("ri-layout-bottom-2-line");
iconList.push("ri-layout-bottom-2-fill");
iconList.push("ri-layout-left-2-line");
iconList.push("ri-layout-left-2-fill");
iconList.push("ri-layout-grid-line");
iconList.push("ri-layout-grid-fill");
iconList.push("ri-layout-masonry-line");
iconList.push("ri-layout-masonry-fill");
iconList.push("ri-collage-line");
iconList.push("ri-collage-fill");
iconList.push("ri-grid-line");
iconList.push("ri-grid-fill");
iconList.push("ri-bug-line");
iconList.push("ri-bug-fill");
iconList.push("ri-bug-2-line");
iconList.push("ri-bug-2-fill");
iconList.push("ri-code-line");
iconList.push("ri-code-fill");
iconList.push("ri-code-s-line");
iconList.push("ri-code-s-fill");
iconList.push("ri-code-s-slash-line");
iconList.push("ri-code-s-slash-fill");
iconList.push("ri-code-box-line");
iconList.push("ri-code-box-fill");
iconList.push("ri-terminal-box-line");
iconList.push("ri-terminal-box-fill");
iconList.push("ri-terminal-line");
iconList.push("ri-terminal-fill");
iconList.push("ri-terminal-window-line");
iconList.push("ri-terminal-window-fill");
iconList.push("ri-parentheses-line");
iconList.push("ri-parentheses-fill");
iconList.push("ri-brackets-line");
iconList.push("ri-brackets-fill");
iconList.push("ri-braces-line");
iconList.push("ri-braces-fill");
iconList.push("ri-command-line");
iconList.push("ri-command-fill");
iconList.push("ri-cursor-line");
iconList.push("ri-cursor-fill");
iconList.push("ri-git-commit-line");
iconList.push("ri-git-commit-fill");
iconList.push("ri-git-pull-request-line");
iconList.push("ri-git-pull-request-fill");
iconList.push("ri-git-merge-line");
iconList.push("ri-git-merge-fill");
iconList.push("ri-git-branch-line");
iconList.push("ri-git-branch-fill");
iconList.push("ri-git-repository-line");
iconList.push("ri-git-repository-fill");
iconList.push("ri-git-repository-commits-line");
iconList.push("ri-git-repository-commits-fill");
iconList.push("ri-git-repository-private-line");
iconList.push("ri-git-repository-private-fill");
iconList.push("ri-html5-line");
iconList.push("ri-html5-fill");
iconList.push("ri-css3-line");
iconList.push("ri-css3-fill");
iconList.push("ri-tv-line");
iconList.push("ri-tv-fill");
iconList.push("ri-tv-2-line");
iconList.push("ri-tv-2-fill");
iconList.push("ri-computer-line");
iconList.push("ri-computer-fill");
iconList.push("ri-mac-line");
iconList.push("ri-mac-fill");
iconList.push("ri-macbook-line");
iconList.push("ri-macbook-fill");
iconList.push("ri-cellphone-line");
iconList.push("ri-cellphone-fill");
iconList.push("ri-smartphone-line");
iconList.push("ri-smartphone-fill");
iconList.push("ri-tablet-line");
iconList.push("ri-tablet-fill");
iconList.push("ri-device-line");
iconList.push("ri-device-fill");
iconList.push("ri-phone-line");
iconList.push("ri-phone-fill");
iconList.push("ri-database-line");
iconList.push("ri-database-fill");
iconList.push("ri-database-2-line");
iconList.push("ri-database-2-fill");
iconList.push("ri-server-line");
iconList.push("ri-server-fill");
iconList.push("ri-hard-drive-line");
iconList.push("ri-hard-drive-fill");
iconList.push("ri-hard-drive-2-line");
iconList.push("ri-hard-drive-2-fill");
iconList.push("ri-install-line");
iconList.push("ri-install-fill");
iconList.push("ri-uninstall-line");
iconList.push("ri-uninstall-fill");
iconList.push("ri-save-line");
iconList.push("ri-save-fill");
iconList.push("ri-save-2-line");
iconList.push("ri-save-2-fill");
iconList.push("ri-save-3-line");
iconList.push("ri-save-3-fill");
iconList.push("ri-sd-card-line");
iconList.push("ri-sd-card-fill");
iconList.push("ri-sd-card-mini-line");
iconList.push("ri-sd-card-mini-fill");
iconList.push("ri-sim-card-line");
iconList.push("ri-sim-card-fill");
iconList.push("ri-sim-card-2-line");
iconList.push("ri-sim-card-2-fill");
iconList.push("ri-dual-sim-1-line");
iconList.push("ri-dual-sim-1-fill");
iconList.push("ri-dual-sim-2-line");
iconList.push("ri-dual-sim-2-fill");
iconList.push("ri-u-disk-line");
iconList.push("ri-u-disk-fill");
iconList.push("ri-battery-line");
iconList.push("ri-battery-fill");
iconList.push("ri-battery-charge-line");
iconList.push("ri-battery-charge-fill");
iconList.push("ri-battery-low-line");
iconList.push("ri-battery-low-fill");
iconList.push("ri-battery-2-line");
iconList.push("ri-battery-2-fill");
iconList.push("ri-battery-2-charge-line");
iconList.push("ri-battery-2-charge-fill");
iconList.push("ri-battery-saver-line");
iconList.push("ri-battery-saver-fill");
iconList.push("ri-battery-share-line");
iconList.push("ri-battery-share-fill");
iconList.push("ri-cast-line");
iconList.push("ri-cast-fill");
iconList.push("ri-airplay-line");
iconList.push("ri-airplay-fill");
iconList.push("ri-cpu-line");
iconList.push("ri-cpu-fill");
iconList.push("ri-gradienter-line");
iconList.push("ri-gradienter-fill");
iconList.push("ri-keyboard-line");
iconList.push("ri-keyboard-fill");
iconList.push("ri-keyboard-box-line");
iconList.push("ri-keyboard-box-fill");
iconList.push("ri-mouse-line");
iconList.push("ri-mouse-fill");
iconList.push("ri-sensor-line");
iconList.push("ri-sensor-fill");
iconList.push("ri-router-line");
iconList.push("ri-router-fill");
iconList.push("ri-radar-line");
iconList.push("ri-radar-fill");
iconList.push("ri-gamepad-line");
iconList.push("ri-gamepad-fill");
iconList.push("ri-remote-control-line");
iconList.push("ri-remote-control-fill");
iconList.push("ri-remote-control-2-line");
iconList.push("ri-remote-control-2-fill");
iconList.push("ri-device-recover-line");
iconList.push("ri-device-recover-fill");
iconList.push("ri-hotspot-line");
iconList.push("ri-hotspot-fill");
iconList.push("ri-phone-find-line");
iconList.push("ri-phone-find-fill");
iconList.push("ri-phone-lock-line");
iconList.push("ri-phone-lock-fill");
iconList.push("ri-rotate-lock-line");
iconList.push("ri-rotate-lock-fill");
iconList.push("ri-restart-line");
iconList.push("ri-restart-fill");
iconList.push("ri-shut-down-line");
iconList.push("ri-shut-down-fill");
iconList.push("ri-fingerprint-line");
iconList.push("ri-fingerprint-fill");
iconList.push("ri-fingerprint-2-line");
iconList.push("ri-fingerprint-2-fill");
iconList.push("ri-barcode-line");
iconList.push("ri-barcode-fill");
iconList.push("ri-barcode-box-line");
iconList.push("ri-barcode-box-fill");
iconList.push("ri-qr-code-line");
iconList.push("ri-qr-code-fill");
iconList.push("ri-qr-scan-line");
iconList.push("ri-qr-scan-fill");
iconList.push("ri-qr-scan-2-line");
iconList.push("ri-qr-scan-2-fill");
iconList.push("ri-scan-line");
iconList.push("ri-scan-fill");
iconList.push("ri-scan-2-line");
iconList.push("ri-scan-2-fill");
iconList.push("ri-rss-line");
iconList.push("ri-rss-fill");
iconList.push("ri-gps-line");
iconList.push("ri-gps-fill");
iconList.push("ri-base-station-line");
iconList.push("ri-base-station-fill");
iconList.push("ri-bluetooth-line");
iconList.push("ri-bluetooth-fill");
iconList.push("ri-bluetooth-connect-line");
iconList.push("ri-bluetooth-connect-fill");
iconList.push("ri-wifi-line");
iconList.push("ri-wifi-fill");
iconList.push("ri-wifi-off-line");
iconList.push("ri-wifi-off-fill");
iconList.push("ri-signal-wifi-line");
iconList.push("ri-signal-wifi-fill");
iconList.push("ri-signal-wifi-1-line");
iconList.push("ri-signal-wifi-1-fill");
iconList.push("ri-signal-wifi-2-line");
iconList.push("ri-signal-wifi-2-fill");
iconList.push("ri-signal-wifi-3-line");
iconList.push("ri-signal-wifi-3-fill");
iconList.push("ri-signal-wifi-error-line");
iconList.push("ri-signal-wifi-error-fill");
iconList.push("ri-signal-wifi-off-line");
iconList.push("ri-signal-wifi-off-fill");
iconList.push("ri-wireless-charging-line");
iconList.push("ri-wireless-charging-fill");
iconList.push("ri-dashboard-2-line");
iconList.push("ri-dashboard-2-fill");
iconList.push("ri-dashboard-3-line");
iconList.push("ri-dashboard-3-fill");
iconList.push("ri-usb-line");
iconList.push("ri-usb-fill");
iconList.push("ri-file-line");
iconList.push("ri-file-fill");
iconList.push("ri-file-2-line");
iconList.push("ri-file-2-fill");
iconList.push("ri-file-3-line");
iconList.push("ri-file-3-fill");
iconList.push("ri-file-4-line");
iconList.push("ri-file-4-fill");
iconList.push("ri-sticky-note-line");
iconList.push("ri-sticky-note-fill");
iconList.push("ri-sticky-note-2-line");
iconList.push("ri-sticky-note-2-fill");
iconList.push("ri-file-edit-line");
iconList.push("ri-file-edit-fill");
iconList.push("ri-draft-line");
iconList.push("ri-draft-fill");
iconList.push("ri-file-paper-line");
iconList.push("ri-file-paper-fill");
iconList.push("ri-file-paper-2-line");
iconList.push("ri-file-paper-2-fill");
iconList.push("ri-file-text-line");
iconList.push("ri-file-text-fill");
iconList.push("ri-file-list-line");
iconList.push("ri-file-list-fill");
iconList.push("ri-file-list-2-line");
iconList.push("ri-file-list-2-fill");
iconList.push("ri-file-list-3-line");
iconList.push("ri-file-list-3-fill");
iconList.push("ri-bill-line");
iconList.push("ri-bill-fill");
iconList.push("ri-file-copy-line");
iconList.push("ri-file-copy-fill");
iconList.push("ri-file-copy-2-line");
iconList.push("ri-file-copy-2-fill");
iconList.push("ri-clipboard-line");
iconList.push("ri-clipboard-fill");
iconList.push("ri-survey-line");
iconList.push("ri-survey-fill");
iconList.push("ri-article-line");
iconList.push("ri-article-fill");
iconList.push("ri-newspaper-line");
iconList.push("ri-newspaper-fill");
iconList.push("ri-file-zip-line");
iconList.push("ri-file-zip-fill");
iconList.push("ri-file-mark-line");
iconList.push("ri-file-mark-fill");
iconList.push("ri-task-line");
iconList.push("ri-task-fill");
iconList.push("ri-todo-line");
iconList.push("ri-todo-fill");
iconList.push("ri-book-line");
iconList.push("ri-book-fill");
iconList.push("ri-book-mark-line");
iconList.push("ri-book-mark-fill");
iconList.push("ri-book-2-line");
iconList.push("ri-book-2-fill");
iconList.push("ri-book-3-line");
iconList.push("ri-book-3-fill");
iconList.push("ri-book-open-line");
iconList.push("ri-book-open-fill");
iconList.push("ri-book-read-line");
iconList.push("ri-book-read-fill");
iconList.push("ri-contacts-book-line");
iconList.push("ri-contacts-book-fill");
iconList.push("ri-contacts-book-2-line");
iconList.push("ri-contacts-book-2-fill");
iconList.push("ri-contacts-book-upload-line");
iconList.push("ri-contacts-book-upload-fill");
iconList.push("ri-booklet-line");
iconList.push("ri-booklet-fill");
iconList.push("ri-file-code-line");
iconList.push("ri-file-code-fill");
iconList.push("ri-file-pdf-line");
iconList.push("ri-file-pdf-fill");
iconList.push("ri-file-word-line");
iconList.push("ri-file-word-fill");
iconList.push("ri-file-ppt-line");
iconList.push("ri-file-ppt-fill");
iconList.push("ri-file-excel-line");
iconList.push("ri-file-excel-fill");
iconList.push("ri-file-word-2-line");
iconList.push("ri-file-word-2-fill");
iconList.push("ri-file-ppt-2-line");
iconList.push("ri-file-ppt-2-fill");
iconList.push("ri-file-excel-2-line");
iconList.push("ri-file-excel-2-fill");
iconList.push("ri-file-hwp-line");
iconList.push("ri-file-hwp-fill");
iconList.push("ri-keynote-line");
iconList.push("ri-keynote-fill");
iconList.push("ri-numbers-line");
iconList.push("ri-numbers-fill");
iconList.push("ri-pages-line");
iconList.push("ri-pages-fill");
iconList.push("ri-file-search-line");
iconList.push("ri-file-search-fill");
iconList.push("ri-file-add-line");
iconList.push("ri-file-add-fill");
iconList.push("ri-file-reduce-line");
iconList.push("ri-file-reduce-fill");
iconList.push("ri-file-settings-line");
iconList.push("ri-file-settings-fill");
iconList.push("ri-file-upload-line");
iconList.push("ri-file-upload-fill");
iconList.push("ri-file-transfer-line");
iconList.push("ri-file-transfer-fill");
iconList.push("ri-file-download-line");
iconList.push("ri-file-download-fill");
iconList.push("ri-file-lock-line");
iconList.push("ri-file-lock-fill");
iconList.push("ri-file-chart-line");
iconList.push("ri-file-chart-fill");
iconList.push("ri-file-chart-2-line");
iconList.push("ri-file-chart-2-fill");
iconList.push("ri-file-music-line");
iconList.push("ri-file-music-fill");
iconList.push("ri-file-gif-line");
iconList.push("ri-file-gif-fill");
iconList.push("ri-file-forbid-line");
iconList.push("ri-file-forbid-fill");
iconList.push("ri-file-info-line");
iconList.push("ri-file-info-fill");
iconList.push("ri-file-warning-line");
iconList.push("ri-file-warning-fill");
iconList.push("ri-file-unknow-line");
iconList.push("ri-file-unknow-fill");
iconList.push("ri-file-user-line");
iconList.push("ri-file-user-fill");
iconList.push("ri-file-shield-line");
iconList.push("ri-file-shield-fill");
iconList.push("ri-file-shield-2-line");
iconList.push("ri-file-shield-2-fill");
iconList.push("ri-file-damage-line");
iconList.push("ri-file-damage-fill");
iconList.push("ri-file-history-line");
iconList.push("ri-file-history-fill");
iconList.push("ri-file-shred-line");
iconList.push("ri-file-shred-fill");
iconList.push("ri-file-cloud-line");
iconList.push("ri-file-cloud-fill");
iconList.push("ri-folder-line");
iconList.push("ri-folder-fill");
iconList.push("ri-folder-2-line");
iconList.push("ri-folder-2-fill");
iconList.push("ri-folder-3-line");
iconList.push("ri-folder-3-fill");
iconList.push("ri-folder-4-line");
iconList.push("ri-folder-4-fill");
iconList.push("ri-folder-5-line");
iconList.push("ri-folder-5-fill");
iconList.push("ri-folders-line");
iconList.push("ri-folders-fill");
iconList.push("ri-folder-add-line");
iconList.push("ri-folder-add-fill");
iconList.push("ri-folder-reduce-line");
iconList.push("ri-folder-reduce-fill");
iconList.push("ri-folder-settings-line");
iconList.push("ri-folder-settings-fill");
iconList.push("ri-folder-upload-line");
iconList.push("ri-folder-upload-fill");
iconList.push("ri-folder-transfer-line");
iconList.push("ri-folder-transfer-fill");
iconList.push("ri-folder-download-line");
iconList.push("ri-folder-download-fill");
iconList.push("ri-folder-lock-line");
iconList.push("ri-folder-lock-fill");
iconList.push("ri-folder-chart-line");
iconList.push("ri-folder-chart-fill");
iconList.push("ri-folder-chart-2-line");
iconList.push("ri-folder-chart-2-fill");
iconList.push("ri-folder-music-line");
iconList.push("ri-folder-music-fill");
iconList.push("ri-folder-forbid-line");
iconList.push("ri-folder-forbid-fill");
iconList.push("ri-folder-info-line");
iconList.push("ri-folder-info-fill");
iconList.push("ri-folder-warning-line");
iconList.push("ri-folder-warning-fill");
iconList.push("ri-folder-unknow-line");
iconList.push("ri-folder-unknow-fill");
iconList.push("ri-folder-user-line");
iconList.push("ri-folder-user-fill");
iconList.push("ri-folder-shield-line");
iconList.push("ri-folder-shield-fill");
iconList.push("ri-folder-shield-2-line");
iconList.push("ri-folder-shield-2-fill");
iconList.push("ri-folder-shared-line");
iconList.push("ri-folder-shared-fill");
iconList.push("ri-folder-received-line");
iconList.push("ri-folder-received-fill");
iconList.push("ri-folder-open-line");
iconList.push("ri-folder-open-fill");
iconList.push("ri-folder-keyhole-line");
iconList.push("ri-folder-keyhole-fill");
iconList.push("ri-folder-zip-line");
iconList.push("ri-folder-zip-fill");
iconList.push("ri-folder-history-line");
iconList.push("ri-folder-history-fill");
iconList.push("ri-markdown-line");
iconList.push("ri-markdown-fill");
iconList.push("ri-bold");
iconList.push("ri-italic");
iconList.push("ri-heading");
iconList.push("ri-text");
iconList.push("ri-font-color");
iconList.push("ri-font-size");
iconList.push("ri-font-size-2");
iconList.push("ri-underline");
iconList.push("ri-emphasis");
iconList.push("ri-emphasis-cn");
iconList.push("ri-strikethrough");
iconList.push("ri-strikethrough-2");
iconList.push("ri-format-clear");
iconList.push("ri-align-left");
iconList.push("ri-align-center");
iconList.push("ri-align-right");
iconList.push("ri-align-justify");
iconList.push("ri-align-top");
iconList.push("ri-align-vertically");
iconList.push("ri-align-bottom");
iconList.push("ri-list-check");
iconList.push("ri-list-check-2");
iconList.push("ri-list-ordered");
iconList.push("ri-list-unordered");
iconList.push("ri-indent-decrease");
iconList.push("ri-indent-increase");
iconList.push("ri-line-height");
iconList.push("ri-text-spacing");
iconList.push("ri-text-wrap");
iconList.push("ri-attachment-2");
iconList.push("ri-link");
iconList.push("ri-link-unlink");
iconList.push("ri-link-m");
iconList.push("ri-link-unlink-m");
iconList.push("ri-separator");
iconList.push("ri-space");
iconList.push("ri-page-separator");
iconList.push("ri-code-view");
iconList.push("ri-double-quotes-l");
iconList.push("ri-double-quotes-r");
iconList.push("ri-single-quotes-l");
iconList.push("ri-single-quotes-r");
iconList.push("ri-table-2");
iconList.push("ri-subscript");
iconList.push("ri-subscript-2");
iconList.push("ri-superscript");
iconList.push("ri-superscript-2");
iconList.push("ri-paragraph");
iconList.push("ri-text-direction-l");
iconList.push("ri-text-direction-r");
iconList.push("ri-functions");
iconList.push("ri-omega");
iconList.push("ri-hashtag");
iconList.push("ri-asterisk");
iconList.push("ri-question-mark");
iconList.push("ri-translate");
iconList.push("ri-translate-2");
iconList.push("ri-a-b");
iconList.push("ri-english-input");
iconList.push("ri-pinyin-input");
iconList.push("ri-wubi-input");
iconList.push("ri-input-cursor-move");
iconList.push("ri-number-1");
iconList.push("ri-number-2");
iconList.push("ri-number-3");
iconList.push("ri-number-4");
iconList.push("ri-number-5");
iconList.push("ri-number-6");
iconList.push("ri-number-7");
iconList.push("ri-number-8");
iconList.push("ri-number-9");
iconList.push("ri-number-0");
iconList.push("ri-sort-asc");
iconList.push("ri-sort-desc");
iconList.push("ri-bring-forward");
iconList.push("ri-send-backward");
iconList.push("ri-bring-to-front");
iconList.push("ri-send-to-back");
iconList.push("ri-h-1");
iconList.push("ri-h-2");
iconList.push("ri-h-3");
iconList.push("ri-h-4");
iconList.push("ri-h-5");
iconList.push("ri-h-6");
iconList.push("ri-insert-column-left");
iconList.push("ri-insert-column-right");
iconList.push("ri-insert-row-top");
iconList.push("ri-insert-row-bottom");
iconList.push("ri-delete-column");
iconList.push("ri-delete-row");
iconList.push("ri-merge-cells-horizontal");
iconList.push("ri-merge-cells-vertical");
iconList.push("ri-split-cells-horizontal");
iconList.push("ri-split-cells-vertical");
iconList.push("ri-flow-chart");
iconList.push("ri-mind-map");
iconList.push("ri-node-tree");
iconList.push("ri-organization-chart");
iconList.push("ri-rounded-corner");
iconList.push("ri-wallet-line");
iconList.push("ri-wallet-fill");
// iconList.push("ri-wallet-2-line");
// iconList.push("ri-wallet-2-fill");
// ​iconList.push("ri-wallet-3-line");
// ​iconList.push("ri-wallet-3-fill");
// ​iconList.push("ri-bank-card-line");
// iconList.push("ri-bank-card-fill");
// iconList.push("ri-bank-card-2-line");
// ​iconList.push("ri-bank-card-2-fill");
// ​iconList.push("ri-secure-payment-line");
// iconList.push("ri-secure-payment-fill");
// iconList.push("ri-refund-line");
// iconList.push("ri-refund-fill");
// iconList.push("ri-refund-2-line");
// iconList.push("ri-refund-2-fill");
// iconList.push("ri-safe-line");
// iconList.push("ri-safe-fill");
// iconList.push("ri-safe-2-line");
// iconList.push("ri-safe-2-fill");
// iconList.push("ri-price-tag-line");
// iconList.push("ri-price-tag-fill");
// iconList.push("ri-price-tag-2-line");
// iconList.push("ri-price-tag-2-fill");
// iconList.push("ri-price-tag-3-line");
// iconList.push("ri-price-tag-3-fill");
// iconList.push("ri-ticket-line");
// iconList.push("ri-ticket-fill");
// iconList.push("ri-ticket-2-line");
// ​iconList.push("ri-ticket-2-fill");
// iconList.push("ri-coupon-line");
// iconList.push("ri-coupon-fill");
// iconList.push("ri-coupon-2-line");
// iconList.push("ri-coupon-2-fill");
// iconList.push("ri-coupon-3-line");
// iconList.push("ri-coupon-3-fill");
// iconList.push("ri-coupon-4-line");
// iconList.push("ri-coupon-4-fill");
// iconList.push("ri-coupon-5-line");
// iconList.push("ri-coupon-5-fill");
iconList.push("ri-shopping-bag-line");
iconList.push("ri-shopping-bag-fill");
iconList.push("ri-shopping-bag-2-line");
iconList.push("ri-shopping-bag-2-fill");
iconList.push("ri-shopping-bag-3-line");
iconList.push("ri-shopping-bag-3-fill");
iconList.push("ri-shopping-basket-line");
iconList.push("ri-shopping-basket-fill");
iconList.push("ri-shopping-basket-2-line");
iconList.push("ri-shopping-basket-2-fill");
iconList.push("ri-shopping-cart-line");
iconList.push("ri-shopping-cart-fill");
iconList.push("ri-shopping-cart-2-line");
iconList.push("ri-shopping-cart-2-fill");
iconList.push("ri-vip-line");
iconList.push("ri-vip-fill");
iconList.push("ri-vip-crown-line");
iconList.push("ri-vip-crown-fill");
iconList.push("ri-vip-crown-2-line");
iconList.push("ri-vip-crown-2-fill");
iconList.push("ri-vip-diamond-line");
iconList.push("ri-vip-diamond-fill");
iconList.push("ri-trophy-line");
iconList.push("ri-trophy-fill");
iconList.push("ri-exchange-line");
iconList.push("ri-exchange-fill");
iconList.push("ri-exchange-box-line");
iconList.push("ri-exchange-box-fill");
iconList.push("ri-swap-line");
iconList.push("ri-swap-fill");
iconList.push("ri-swap-box-line");
iconList.push("ri-swap-box-fill");
iconList.push("ri-exchange-dollar-line");
iconList.push("ri-exchange-dollar-fill");
iconList.push("ri-exchange-cny-line");
iconList.push("ri-exchange-cny-fill");
iconList.push("ri-exchange-funds-line");
iconList.push("ri-exchange-funds-fill");
iconList.push("ri-increase-decrease-line");
iconList.push("ri-increase-decrease-fill");
iconList.push("ri-percent-line");
iconList.push("ri-percent-fill");
iconList.push("ri-copper-coin-line");
iconList.push("ri-copper-coin-fill");
iconList.push("ri-copper-diamond-line");
iconList.push("ri-copper-diamond-fill");
iconList.push("ri-money-cny-box-line");
iconList.push("ri-money-cny-box-fill");
iconList.push("ri-money-cny-circle-line");
iconList.push("ri-money-cny-circle-fill");
iconList.push("ri-money-dollar-box-line");
iconList.push("ri-money-dollar-box-fill");
iconList.push("ri-money-dollar-circle-line");
iconList.push("ri-money-dollar-circle-fill");
iconList.push("ri-money-euro-box-line");
iconList.push("ri-money-euro-box-fill");
iconList.push("ri-money-euro-circle-line");
iconList.push("ri-money-euro-circle-fill");
iconList.push("ri-money-pound-box-line");
iconList.push("ri-money-pound-box-fill");
iconList.push("ri-money-pound-circle-line");
iconList.push("ri-money-pound-circle-fill");
iconList.push("ri-bit-coin-line");
iconList.push("ri-bit-coin-fill");
iconList.push("ri-coin-line");
iconList.push("ri-coin-fill");
iconList.push("ri-coins-line");
iconList.push("ri-coins-fill");
iconList.push("ri-currency-line");
iconList.push("ri-currency-fill");
iconList.push("ri-funds-line");
iconList.push("ri-funds-fill");
iconList.push("ri-funds-box-line");
iconList.push("ri-funds-box-fill");
iconList.push("ri-red-packet-line");
iconList.push("ri-red-packet-fill");
iconList.push("ri-water-flash-line");
iconList.push("ri-water-flash-fill");
iconList.push("ri-stock-line");
iconList.push("ri-stock-fill");
iconList.push("ri-auction-line");
iconList.push("ri-auction-fill");
iconList.push("ri-gift-line");
iconList.push("ri-gift-fill");
// ​iconList.push("ri-gift-2-line"); ​iconList.push("ri-gift-2-fill"); ​iconList.push("ri-hand-coin-line"); ​iconList.push("ri-hand-coin-fill"); ​
// iconList.push("ri-hand-heart-line"); ​iconList.push("ri-hand-heart-fill"); ​iconList.push("ri-24-hours-line"); ​iconList.push("ri-24-hours-fill"); ​iconList.push("ri-heart-line"); ​
// iconList.push("ri-heart-fill"); ​iconList.push("ri-heart-2-line"); ​iconList.push("ri-heart-2-fill"); ​iconList.push("ri-heart-3-line"); ​iconList.push("ri-heart-3-fill"); ​
// iconList.push("ri-heart-add-line"); ​iconList.push("ri-heart-add-fill"); ​iconList.push("ri-dislike-line"); ​iconList.push("ri-dislike-fill"); ​iconList.push("ri-hearts-line"); ​
// iconList.push("ri-hearts-fill"); ​iconList.push("ri-heart-pulse-line"); ​iconList.push("ri-heart-pulse-fill"); ​iconList.push("ri-pulse-line"); ​iconList.push("ri-pulse-fill"); ​
// iconList.push("ri-empathize-line"); ​iconList.push("ri-empathize-fill"); ​iconList.push("ri-nurse-line"); ​iconList.push("ri-nurse-fill"); ​iconList.push("ri-dossier-line"); ​
// iconList.push("ri-dossier-fill"); ​iconList.push("ri-health-book-line"); ​iconList.push("ri-health-book-fill"); ​iconList.push("ri-first-aid-kit-line"); ​
// iconList.push("ri-first-aid-kit-fill"); ​iconList.push("ri-capsule-line"); ​iconList.push("ri-capsule-fill"); ​iconList.push("ri-medicine-bottle-line"); ​
// iconList.push("ri-medicine-bottle-fill"); ​iconList.push("ri-flask-line"); ​iconList.push("ri-flask-fill"); ​iconList.push("ri-test-tube-line"); ​iconList.push("ri-test-tube-fill"); ​
// iconList.push("ri-microscope-line"); ​iconList.push("ri-microscope-fill"); ​iconList.push("ri-hand-sanitizer-line"); ​iconList.push("ri-hand-sanitizer-fill"); ​
// iconList.push("ri-mental-health-line"); ​iconList.push("ri-mental-health-fill"); ​iconList.push("ri-psychotherapy-line"); ​iconList.push("ri-psychotherapy-fill"); ​
// iconList.push("ri-stethoscope-line"); ​iconList.push("ri-stethoscope-fill"); ​iconList.push("ri-syringe-line"); ​iconList.push("ri-syringe-fill"); ​iconList.push("ri-thermometer-line"); ​
// iconList.push("ri-thermometer-fill"); ​iconList.push("ri-infrared-thermometer-line"); ​iconList.push("ri-infrared-thermometer-fill"); ​
// iconList.push("ri-surgical-mask-line"); ​iconList.push("ri-surgical-mask-fill"); ​iconList.push("ri-virus-line"); ​iconList.push("ri-virus-fill"); ​iconList.push("ri-lungs-line"); ​
// iconList.push("ri-lungs-fill"); ​iconList.push("ri-rest-time-line"); ​iconList.push("ri-rest-time-fill"); ​iconList.push("ri-zzz-line"); ​iconList.push("ri-zzz-fill"); ​iconList.push("ri-alipay-line"); ​
// iconList.push("ri-alipay-fill"); ​iconList.push("ri-amazon-line"); ​iconList.push("ri-amazon-fill"); ​iconList.push("ri-android-line"); ​iconList.push("ri-android-fill"); ​
// iconList.push("ri-angularjs-line"); ​iconList.push("ri-angularjs-fill"); ​iconList.push("ri-app-store-line"); ​iconList.push("ri-app-store-fill"); ​iconList.push("ri-apple-line"); ​
// iconList.push("ri-apple-fill"); ​iconList.push("ri-baidu-line"); ​iconList.push("ri-baidu-fill"); ​iconList.push("ri-behance-line"); ​iconList.push("ri-behance-fill"); ​
// iconList.push("ri-bilibili-line"); ​iconList.push("ri-bilibili-fill"); ​iconList.push("ri-centos-line"); ​iconList.push("ri-centos-fill"); ​iconList.push("ri-chrome-line"); ​
// iconList.push("ri-chrome-fill"); ​iconList.push("ri-codepen-line"); ​iconList.push("ri-codepen-fill"); ​iconList.push("ri-coreos-line"); ​iconList.push("ri-coreos-fill"); ​
// iconList.push("ri-dingding-line"); ​iconList.push("ri-dingding-fill"); ​iconList.push("ri-discord-line"); ​iconList.push("ri-discord-fill"); ​iconList.push("ri-disqus-line"); ​
// iconList.push("ri-disqus-fill"); ​iconList.push("ri-douban-line"); ​iconList.push("ri-douban-fill"); ​iconList.push("ri-dribbble-line"); ​iconList.push("ri-dribbble-fill"); ​
// iconList.push("ri-drive-line"); ​iconList.push("ri-drive-fill"); ​iconList.push("ri-dropbox-line"); ​iconList.push("ri-dropbox-fill"); ​iconList.push("ri-edge-line"); ​iconList.push("ri-edge-fill"); ​
// iconList.push("ri-evernote-line"); ​iconList.push("ri-evernote-fill"); ​iconList.push("ri-facebook-line"); ​iconList.push("ri-facebook-fill"); ​iconList.push("ri-facebook-circle-line"); ​
// iconList.push("ri-facebook-circle-fill"); ​iconList.push("ri-facebook-box-line"); ​iconList.push("ri-facebook-box-fill"); ​iconList.push("ri-finder-line"); ​
// iconList.push("ri-finder-fill"); ​iconList.push("ri-firefox-line"); ​iconList.push("ri-firefox-fill"); ​iconList.push("ri-flutter-line"); ​iconList.push("ri-flutter-fill"); ​
// iconList.push("ri-gatsby-line"); ​iconList.push("ri-gatsby-fill"); ​iconList.push("ri-github-line"); ​iconList.push("ri-github-fill"); ​iconList.push("ri-gitlab-line"); ​iconList.push("ri-gitlab-fill"); ​
// iconList.push("ri-google-line"); ​iconList.push("ri-google-fill"); ​iconList.push("ri-google-play-line"); ​iconList.push("ri-google-play-fill"); ​iconList.push("ri-honor-of-kings-line"); ​
// iconList.push("ri-honor-of-kings-fill"); ​iconList.push("ri-ie-line"); ​iconList.push("ri-ie-fill"); ​iconList.push("ri-instagram-line"); ​iconList.push("ri-instagram-fill"); ​
// iconList.push("ri-invision-line"); ​iconList.push("ri-invision-fill"); ​iconList.push("ri-kakao-talk-line"); ​iconList.push("ri-kakao-talk-fill"); ​iconList.push("ri-line-line"); ​
// iconList.push("ri-line-fill"); ​iconList.push("ri-linkedin-line"); ​iconList.push("ri-linkedin-fill"); ​iconList.push("ri-linkedin-box-line"); ​iconList.push("ri-linkedin-box-fill"); ​
// iconList.push("ri-mastercard-line"); ​iconList.push("ri-mastercard-fill"); ​iconList.push("ri-mastodon-line"); ​iconList.push("ri-mastodon-fill"); ​iconList.push("ri-medium-line"); ​
// iconList.push("ri-medium-fill"); ​iconList.push("ri-messenger-line"); ​iconList.push("ri-messenger-fill"); ​iconList.push("ri-microsoft-line"); ​iconList.push("ri-microsoft-fill"); ​
// iconList.push("ri-mini-program-line"); ​iconList.push("ri-mini-program-fill"); ​iconList.push("ri-netease-cloud-music-line"); ​iconList.push("ri-netease-cloud-music-fill"); ​
// iconList.push("ri-netflix-line"); ​iconList.push("ri-netflix-fill"); ​iconList.push("ri-npmjs-line"); ​iconList.push("ri-npmjs-fill"); ​iconList.push("ri-open-source-line"); ​
// iconList.push("ri-open-source-fill"); ​iconList.push("ri-opera-line"); ​iconList.push("ri-opera-fill"); ​iconList.push("ri-patreon-line"); ​iconList.push("ri-patreon-fill"); ​
// iconList.push("ri-paypal-line"); ​iconList.push("ri-paypal-fill"); ​iconList.push("ri-pinterest-line"); ​iconList.push("ri-pinterest-fill"); ​iconList.push("ri-pixelfed-line"); ​
// iconList.push("ri-pixelfed-fill"); ​iconList.push("ri-playstation-line"); ​iconList.push("ri-playstation-fill"); ​iconList.push("ri-product-hunt-line"); ​
// iconList.push("ri-product-hunt-fill"); ​iconList.push("ri-qq-line"); ​iconList.push("ri-qq-fill"); ​iconList.push("ri-reactjs-line"); ​iconList.push("ri-reactjs-fill"); ​iconList.push("ri-reddit-line"); ​
// iconList.push("ri-reddit-fill"); ​iconList.push("ri-remixicon-line"); ​iconList.push("ri-remixicon-fill"); ​iconList.push("ri-safari-line"); ​iconList.push("ri-safari-fill"); ​
// iconList.push("ri-skype-line"); ​iconList.push("ri-skype-fill"); ​iconList.push("ri-slack-line"); ​iconList.push("ri-slack-fill"); ​iconList.push("ri-snapchat-line"); ​iconList.push("ri-snapchat-fill"); ​
// iconList.push("ri-soundcloud-line"); ​iconList.push("ri-soundcloud-fill"); ​iconList.push("ri-spectrum-line"); ​iconList.push("ri-spectrum-fill"); ​iconList.push("ri-spotify-line"); ​
// iconList.push("ri-spotify-fill"); ​iconList.push("ri-stack-overflow-line"); ​iconList.push("ri-stack-overflow-fill"); ​iconList.push("ri-stackshare-line"); ​
// iconList.push("ri-stackshare-fill"); ​iconList.push("ri-steam-line"); ​iconList.push("ri-steam-fill"); ​iconList.push("ri-switch-line"); ​iconList.push("ri-switch-fill"); ​
// iconList.push("ri-taobao-line"); ​iconList.push("ri-taobao-fill"); ​iconList.push("ri-telegram-line"); ​iconList.push("ri-telegram-fill"); ​iconList.push("ri-trello-line"); ​
// iconList.push("ri-trello-fill"); ​iconList.push("ri-tumblr-line"); ​iconList.push("ri-tumblr-fill"); ​iconList.push("ri-twitch-line"); ​iconList.push("ri-twitch-fill"); ​
// iconList.push("ri-twitter-line"); ​iconList.push("ri-twitter-fill"); ​iconList.push("ri-ubuntu-line"); ​iconList.push("ri-ubuntu-fill"); ​iconList.push("ri-unsplash-line"); ​
// iconList.push("ri-unsplash-fill"); ​iconList.push("ri-vimeo-line"); ​iconList.push("ri-vimeo-fill"); ​iconList.push("ri-visa-line"); ​iconList.push("ri-visa-fill"); ​iconList.push("ri-vuejs-line"); ​
// iconList.push("ri-vuejs-fill"); ​iconList.push("ri-wechat-line"); ​iconList.push("ri-wechat-fill"); ​iconList.push("ri-wechat-2-line"); ​iconList.push("ri-wechat-2-fill"); ​
// iconList.push("ri-wechat-pay-line"); ​iconList.push("ri-wechat-pay-fill"); ​iconList.push("ri-weibo-line"); ​iconList.push("ri-weibo-fill"); ​iconList.push("ri-whatsapp-line"); ​
// iconList.push("ri-whatsapp-fill"); ​iconList.push("ri-windows-line"); ​iconList.push("ri-windows-fill"); ​iconList.push("ri-xbox-line"); ​iconList.push("ri-xbox-fill"); ​iconList.push("ri-xing-line"); ​
// iconList.push("ri-xing-fill"); ​iconList.push("ri-youtube-line"); ​iconList.push("ri-youtube-fill"); ​iconList.push("ri-zcool-line"); ​iconList.push("ri-zcool-fill"); ​iconList.push("ri-zhihu-line"); ​
// iconList.push("ri-zhihu-fill"); ​iconList.push("ri-map-pin-line"); ​iconList.push("ri-map-pin-fill"); ​iconList.push("ri-map-pin-2-line"); ​iconList.push("ri-map-pin-2-fill"); ​
// iconList.push("ri-map-pin-3-line"); ​iconList.push("ri-map-pin-3-fill"); ​iconList.push("ri-map-pin-4-line"); ​iconList.push("ri-map-pin-4-fill"); ​iconList.push("ri-map-pin-5-line"); ​
// iconList.push("ri-map-pin-5-fill"); ​iconList.push("ri-map-pin-add-line"); ​iconList.push("ri-map-pin-add-fill"); ​iconList.push("ri-map-pin-range-line"); ​
// iconList.push("ri-map-pin-range-fill"); ​iconList.push("ri-map-pin-time-line"); ​iconList.push("ri-map-pin-time-fill"); ​iconList.push("ri-map-pin-user-line"); ​
// iconList.push("ri-map-pin-user-fill"); ​iconList.push("ri-pin-distance-line"); ​iconList.push("ri-pin-distance-fill"); ​iconList.push("ri-pushpin-line"); ​
// iconList.push("ri-pushpin-fill"); ​iconList.push("ri-pushpin-2-line"); ​iconList.push("ri-pushpin-2-fill"); ​iconList.push("ri-compass-line"); ​iconList.push("ri-compass-fill"); ​
// iconList.push("ri-compass-2-line"); ​iconList.push("ri-compass-2-fill"); ​iconList.push("ri-compass-3-line"); ​iconList.push("ri-compass-3-fill"); ​iconList.push("ri-compass-4-line"); ​
// iconList.push("ri-compass-4-fill"); ​iconList.push("ri-compass-discover-line"); ​iconList.push("ri-compass-discover-fill"); ​iconList.push("ri-anchor-line"); ​
// iconList.push("ri-anchor-fill"); ​iconList.push("ri-china-railway-line"); ​iconList.push("ri-china-railway-fill"); ​iconList.push("ri-space-ship-line"); ​
// iconList.push("ri-space-ship-fill"); ​iconList.push("ri-rocket-line"); ​iconList.push("ri-rocket-fill"); ​iconList.push("ri-rocket-2-line"); ​iconList.push("ri-rocket-2-fill"); ​
// iconList.push("ri-map-line"); ​iconList.push("ri-map-fill"); ​iconList.push("ri-map-2-line"); ​iconList.push("ri-map-2-fill"); ​iconList.push("ri-treasure-map-line"); ​
// iconList.push("ri-treasure-map-fill"); ​iconList.push("ri-road-map-line"); ​iconList.push("ri-road-map-fill"); ​iconList.push("ri-earth-line"); ​iconList.push("ri-earth-fill"); ​
// iconList.push("ri-globe-line"); ​iconList.push("ri-globe-fill"); ​iconList.push("ri-parking-line"); ​iconList.push("ri-parking-fill"); ​iconList.push("ri-parking-box-line"); ​
// iconList.push("ri-parking-box-fill"); ​iconList.push("ri-route-line"); ​iconList.push("ri-route-fill"); ​iconList.push("ri-guide-line"); ​iconList.push("ri-guide-fill"); ​
// iconList.push("ri-gas-station-line"); ​iconList.push("ri-gas-station-fill"); ​iconList.push("ri-charging-pile-line"); ​iconList.push("ri-charging-pile-fill"); ​
// iconList.push("ri-charging-pile-2-line"); ​iconList.push("ri-charging-pile-2-fill"); ​iconList.push("ri-car-line"); ​iconList.push("ri-car-fill"); ​iconList.push("ri-car-washing-line"); ​
// iconList.push("ri-car-washing-fill"); ​iconList.push("ri-roadster-line"); ​iconList.push("ri-roadster-fill"); ​iconList.push("ri-taxi-line"); ​iconList.push("ri-taxi-fill"); ​
// iconList.push("ri-taxi-wifi-line"); ​iconList.push("ri-taxi-wifi-fill"); ​iconList.push("ri-police-car-line"); ​iconList.push("ri-police-car-fill"); ​iconList.push("ri-bus-line"); ​
// iconList.push("ri-bus-fill"); ​iconList.push("ri-bus-2-line"); ​iconList.push("ri-bus-2-fill"); ​iconList.push("ri-bus-wifi-line"); ​iconList.push("ri-bus-wifi-fill"); ​iconList.push("ri-truck-line"); ​
// iconList.push("ri-truck-fill"); ​iconList.push("ri-train-line"); ​iconList.push("ri-train-fill"); ​iconList.push("ri-train-wifi-line"); ​iconList.push("ri-train-wifi-fill"); ​
// iconList.push("ri-subway-line"); ​iconList.push("ri-subway-fill"); ​iconList.push("ri-subway-wifi-line"); ​iconList.push("ri-subway-wifi-fill"); ​iconList.push("ri-flight-takeoff-line"); ​
// iconList.push("ri-flight-takeoff-fill"); ​iconList.push("ri-flight-land-line"); ​iconList.push("ri-flight-land-fill"); ​iconList.push("ri-plane-line"); ​iconList.push("ri-plane-fill"); ​
// iconList.push("ri-sailboat-line"); ​iconList.push("ri-sailboat-fill"); ​iconList.push("ri-ship-line"); ​iconList.push("ri-ship-fill"); ​iconList.push("ri-ship-2-line"); ​iconList.push("ri-ship-2-fill"); ​
// iconList.push("ri-bike-line"); ​iconList.push("ri-bike-fill"); ​iconList.push("ri-e-bike-line"); ​iconList.push("ri-e-bike-fill"); ​iconList.push("ri-e-bike-2-line"); ​iconList.push("ri-e-bike-2-fill"); ​
// iconList.push("ri-takeaway-line"); ​iconList.push("ri-takeaway-fill"); ​iconList.push("ri-motorbike-line"); ​iconList.push("ri-motorbike-fill"); ​iconList.push("ri-caravan-line"); ​
// iconList.push("ri-caravan-fill"); ​iconList.push("ri-walk-line"); ​iconList.push("ri-walk-fill"); ​iconList.push("ri-run-line"); ​iconList.push("ri-run-fill"); ​iconList.push("ri-riding-line"); ​
// iconList.push("ri-riding-fill"); ​iconList.push("ri-barricade-line"); ​iconList.push("ri-barricade-fill"); ​iconList.push("ri-footprint-line"); ​iconList.push("ri-footprint-fill"); ​
// iconList.push("ri-traffic-light-line"); ​iconList.push("ri-traffic-light-fill"); ​iconList.push("ri-signal-tower-line"); ​iconList.push("ri-signal-tower-fill"); ​
// iconList.push("ri-restaurant-line"); ​iconList.push("ri-restaurant-fill"); ​iconList.push("ri-restaurant-2-line"); ​iconList.push("ri-restaurant-2-fill"); ​iconList.push("ri-cup-line"); ​
// iconList.push("ri-cup-fill"); ​iconList.push("ri-goblet-line"); ​iconList.push("ri-goblet-fill"); ​iconList.push("ri-hotel-bed-line"); ​iconList.push("ri-hotel-bed-fill"); ​
// iconList.push("ri-navigation-line"); ​iconList.push("ri-navigation-fill"); ​iconList.push("ri-oil-line"); ​iconList.push("ri-oil-fill"); ​iconList.push("ri-direction-line"); ​
// iconList.push("ri-direction-fill"); ​iconList.push("ri-steering-line"); ​iconList.push("ri-steering-fill"); ​iconList.push("ri-steering-2-line"); ​iconList.push("ri-steering-2-fill"); ​
// iconList.push("ri-lifebuoy-line"); ​iconList.push("ri-lifebuoy-fill"); ​iconList.push("ri-passport-line"); ​iconList.push("ri-passport-fill"); ​iconList.push("ri-suitcase-line"); ​
// iconList.push("ri-suitcase-fill"); ​iconList.push("ri-suitcase-2-line"); ​iconList.push("ri-suitcase-2-fill"); ​iconList.push("ri-suitcase-3-line"); ​iconList.push("ri-suitcase-3-fill"); ​
// iconList.push("ri-luggage-deposit-line"); ​iconList.push("ri-luggage-deposit-fill"); ​iconList.push("ri-luggage-cart-line"); ​iconList.push("ri-luggage-cart-fill"); ​
// iconList.push("ri-image-line"); ​iconList.push("ri-image-fill"); ​iconList.push("ri-image-2-line"); ​iconList.push("ri-image-2-fill"); ​iconList.push("ri-image-add-line");
iconList.push("ri-image-add-fill");
iconList.push("ri-image-edit-line");
iconList.push("ri-image-edit-fill");
iconList.push("ri-landscape-line");
iconList.push("ri-landscape-fill");
iconList.push("ri-gallery-line");
iconList.push("ri-gallery-fill");
iconList.push("ri-gallery-upload-line");
iconList.push("ri-gallery-upload-fill");
iconList.push("ri-video-line");
iconList.push("ri-video-fill");
iconList.push("ri-movie-line");
iconList.push("ri-movie-fill");
iconList.push("ri-movie-2-line");
iconList.push("ri-movie-2-fill");
iconList.push("ri-film-line");
iconList.push("ri-film-fill");
iconList.push("ri-clapperboard-line");
iconList.push("ri-clapperboard-fill");
iconList.push("ri-vidicon-line");
iconList.push("ri-vidicon-fill");
iconList.push("ri-vidicon-2-line");
iconList.push("ri-vidicon-2-fill");
iconList.push("ri-live-line");
iconList.push("ri-live-fill");
iconList.push("ri-video-add-line");
iconList.push("ri-video-add-fill");
iconList.push("ri-video-upload-line");
iconList.push("ri-video-upload-fill");
iconList.push("ri-video-download-line");
iconList.push("ri-video-download-fill");
iconList.push("ri-dv-line");
iconList.push("ri-dv-fill");
iconList.push("ri-camera-line");
iconList.push("ri-camera-fill");
iconList.push("ri-camera-off-line");
iconList.push("ri-camera-off-fill");
iconList.push("ri-camera-2-line");
iconList.push("ri-camera-2-fill");
iconList.push("ri-camera-3-line");
iconList.push("ri-camera-3-fill");
iconList.push("ri-camera-lens-line");
iconList.push("ri-camera-lens-fill");
iconList.push("ri-camera-switch-line");
iconList.push("ri-camera-switch-fill");
iconList.push("ri-polaroid-line");
iconList.push("ri-polaroid-fill");
iconList.push("ri-polaroid-2-line");
iconList.push("ri-polaroid-2-fill");
iconList.push("ri-phone-camera-line");
iconList.push("ri-phone-camera-fill");
iconList.push("ri-webcam-line");
iconList.push("ri-webcam-fill");
iconList.push("ri-mv-line");
iconList.push("ri-mv-fill");
iconList.push("ri-music-line");
iconList.push("ri-music-fill");
iconList.push("ri-music-2-line");
iconList.push("ri-music-2-fill");
iconList.push("ri-disc-line");
iconList.push("ri-disc-fill");
iconList.push("ri-album-line");
iconList.push("ri-album-fill");
iconList.push("ri-dvd-line");
iconList.push("ri-dvd-fill");
iconList.push("ri-headphone-line");
iconList.push("ri-headphone-fill");
iconList.push("ri-radio-line");
iconList.push("ri-radio-fill");
iconList.push("ri-radio-2-line");
iconList.push("ri-radio-2-fill");
iconList.push("ri-tape-line");
iconList.push("ri-tape-fill");
iconList.push("ri-mic-line");
iconList.push("ri-mic-fill");
iconList.push("ri-mic-2-line");
iconList.push("ri-mic-2-fill");
iconList.push("ri-mic-off-line");
iconList.push("ri-mic-off-fill");
iconList.push("ri-volume-down-line");
iconList.push("ri-volume-down-fill");
iconList.push("ri-volume-mute-line");
iconList.push("ri-volume-mute-fill");
iconList.push("ri-volume-up-line");
iconList.push("ri-volume-up-fill");
iconList.push("ri-volume-vibrate-line");
iconList.push("ri-volume-vibrate-fill");
iconList.push("ri-volume-off-vibrate-line");
iconList.push("ri-volume-off-vibrate-fill");
iconList.push("ri-speaker-line");
iconList.push("ri-speaker-fill");
iconList.push("ri-speaker-2-line");
iconList.push("ri-speaker-2-fill");
// iconList.push("ri-speaker-3-line"); ​iconList.push("ri-speaker-3-fill"); ​iconList.push("ri-surround-sound-line"); ​iconList.push("ri-surround-sound-fill"); ​
// iconList.push("ri-broadcast-line"); ​iconList.push("ri-broadcast-fill"); ​iconList.push("ri-notification-line"); ​iconList.push("ri-notification-fill"); ​
// iconList.push("ri-notification-2-line"); ​iconList.push("ri-notification-2-fill"); ​iconList.push("ri-notification-3-line"); ​iconList.push("ri-notification-3-fill"); ​
// iconList.push("ri-notification-4-line"); ​iconList.push("ri-notification-4-fill"); ​iconList.push("ri-notification-off-line"); ​iconList.push("ri-notification-off-fill"); ​
// iconList.push("ri-play-circle-line"); ​iconList.push("ri-play-circle-fill"); ​iconList.push("ri-pause-circle-line"); ​iconList.push("ri-pause-circle-fill"); ​
// iconList.push("ri-record-circle-line"); ​iconList.push("ri-record-circle-fill"); ​iconList.push("ri-stop-circle-line"); ​iconList.push("ri-stop-circle-fill"); ​
// iconList.push("ri-eject-line"); ​iconList.push("ri-eject-fill"); ​iconList.push("ri-play-line"); ​iconList.push("ri-play-fill"); ​iconList.push("ri-pause-line"); ​iconList.push("ri-pause-fill"); ​
// iconList.push("ri-stop-line"); ​iconList.push("ri-stop-fill"); ​iconList.push("ri-rewind-line"); ​iconList.push("ri-rewind-fill"); ​iconList.push("ri-speed-line"); ​iconList.push("ri-speed-fill"); ​
// iconList.push("ri-skip-back-line"); ​iconList.push("ri-skip-back-fill"); ​iconList.push("ri-skip-forward-line"); ​iconList.push("ri-skip-forward-fill"); ​
// iconList.push("ri-play-mini-line"); ​iconList.push("ri-play-mini-fill"); ​iconList.push("ri-pause-mini-line"); ​iconList.push("ri-pause-mini-fill"); ​iconList.push("ri-stop-mini-line"); ​
// iconList.push("ri-stop-mini-fill"); ​iconList.push("ri-rewind-mini-line"); ​iconList.push("ri-rewind-mini-fill"); ​iconList.push("ri-speed-mini-line"); ​
// iconList.push("ri-speed-mini-fill"); ​iconList.push("ri-skip-back-mini-line"); ​iconList.push("ri-skip-back-mini-fill"); ​iconList.push("ri-skip-forward-mini-line"); ​
// iconList.push("ri-skip-forward-mini-fill"); ​iconList.push("ri-repeat-line"); ​iconList.push("ri-repeat-fill"); ​iconList.push("ri-repeat-2-line"); ​iconList.push("ri-repeat-2-fill"); ​
// iconList.push("ri-repeat-one-line"); ​iconList.push("ri-repeat-one-fill"); ​iconList.push("ri-order-play-line"); ​iconList.push("ri-order-play-fill"); ​iconList.push("ri-shuffle-line"); ​
// iconList.push("ri-shuffle-fill"); ​iconList.push("ri-play-list-line"); ​iconList.push("ri-play-list-fill"); ​iconList.push("ri-play-list-2-line"); ​iconList.push("ri-play-list-2-fill"); ​
// iconList.push("ri-play-list-add-line"); ​iconList.push("ri-play-list-add-fill"); ​iconList.push("ri-fullscreen-line"); ​iconList.push("ri-fullscreen-fill"); ​
// iconList.push("ri-fullscreen-exit-line"); ​iconList.push("ri-fullscreen-exit-fill"); ​iconList.push("ri-equalizer-line"); ​iconList.push("ri-equalizer-fill"); ​
// iconList.push("ri-sound-module-line"); ​iconList.push("ri-sound-module-fill"); ​iconList.push("ri-rhythm-line"); ​iconList.push("ri-rhythm-fill"); ​iconList.push("ri-voiceprint-line"); ​
// iconList.push("ri-voiceprint-fill"); ​iconList.push("ri-hq-line"); ​iconList.push("ri-hq-fill"); ​iconList.push("ri-hd-line"); ​iconList.push("ri-hd-fill"); ​iconList.push("ri-4k-line"); ​iconList.push("ri-4k-fill"); ​
// iconList.push("ri-closed-captioning-line"); ​iconList.push("ri-closed-captioning-fill"); ​iconList.push("ri-aspect-ratio-line"); ​iconList.push("ri-aspect-ratio-fill"); ​
// iconList.push("ri-picture-in-picture-line"); ​iconList.push("ri-picture-in-picture-fill"); ​iconList.push("ri-picture-in-picture-2-line"); ​
// iconList.push("ri-picture-in-picture-2-fill"); ​iconList.push("ri-picture-in-picture-exit-line"); ​iconList.push("ri-picture-in-picture-exit-fill"); ​
// iconList.push("ri-apps-line"); ​iconList.push("ri-apps-fill"); ​iconList.push("ri-apps-2-line"); ​iconList.push("ri-apps-2-fill"); ​iconList.push("ri-function-line"); ​iconList.push("ri-function-fill"); ​
// iconList.push("ri-dashboard-line"); ​iconList.push("ri-dashboard-fill"); ​iconList.push("ri-menu-line"); ​iconList.push("ri-menu-fill"); ​iconList.push("ri-menu-2-line"); ​
// iconList.push("ri-menu-2-fill"); ​iconList.push("ri-menu-3-line"); ​iconList.push("ri-menu-3-fill"); ​iconList.push("ri-menu-4-line"); ​iconList.push("ri-menu-4-fill"); ​iconList.push("ri-menu-5-line"); ​
// iconList.push("ri-menu-5-fill"); ​iconList.push("ri-menu-add-line"); ​iconList.push("ri-menu-add-fill"); ​iconList.push("ri-menu-fold-line"); ​iconList.push("ri-menu-fold-fill"); ​
// iconList.push("ri-menu-unfold-line"); ​iconList.push("ri-menu-unfold-fill"); ​iconList.push("ri-more-line"); ​iconList.push("ri-more-fill"); ​iconList.push("ri-more-2-line"); ​
// iconList.push("ri-more-2-fill"); ​iconList.push("ri-star-line"); ​iconList.push("ri-star-fill"); ​iconList.push("ri-star-s-line"); ​iconList.push("ri-star-s-fill"); ​iconList.push("ri-star-half-line");
iconList.push("ri-star-half-fill");
iconList.push("ri-star-half-s-line");
iconList.push("ri-star-half-s-fill");
iconList.push("ri-settings-line");
iconList.push("ri-settings-fill");
iconList.push("ri-settings-2-line");
iconList.push("ri-settings-2-fill");
iconList.push("ri-settings-3-line");
iconList.push("ri-settings-3-fill");
iconList.push("ri-settings-4-line");
iconList.push("ri-settings-4-fill");
iconList.push("ri-settings-5-line");
iconList.push("ri-settings-5-fill");
iconList.push("ri-settings-6-line");
iconList.push("ri-settings-6-fill");
iconList.push("ri-list-settings-line");
iconList.push("ri-list-settings-fill");
iconList.push("ri-forbid-line");
iconList.push("ri-forbid-fill");
iconList.push("ri-forbid-2-line");
iconList.push("ri-forbid-2-fill");
iconList.push("ri-information-line");
iconList.push("ri-information-fill");
iconList.push("ri-error-warning-line");
iconList.push("ri-error-warning-fill");
iconList.push("ri-question-line");
iconList.push("ri-question-fill");
iconList.push("ri-alert-line");
iconList.push("ri-alert-fill");
iconList.push("ri-spam-line");
iconList.push("ri-spam-fill");
iconList.push("ri-spam-2-line");
iconList.push("ri-spam-2-fill");
iconList.push("ri-spam-3-line");
iconList.push("ri-spam-3-fill");
iconList.push("ri-checkbox-blank-line");
iconList.push("ri-checkbox-blank-fill");
iconList.push("ri-checkbox-line");
iconList.push("ri-checkbox-fill");
iconList.push("ri-checkbox-indeterminate-line");
iconList.push("ri-checkbox-indeterminate-fill");
iconList.push("ri-add-box-line");
iconList.push("ri-add-box-fill");
iconList.push("ri-checkbox-blank-circle-line");
iconList.push("ri-checkbox-blank-circle-fill");
iconList.push("ri-checkbox-circle-line");
iconList.push("ri-checkbox-circle-fill");
iconList.push("ri-indeterminate-circle-line");
iconList.push("ri-indeterminate-circle-fill");
iconList.push("ri-add-circle-line");
iconList.push("ri-add-circle-fill");
iconList.push("ri-close-circle-line");
iconList.push("ri-close-circle-fill");
iconList.push("ri-radio-button-line");
iconList.push("ri-radio-button-fill");
iconList.push("ri-checkbox-multiple-blank-line");
iconList.push("ri-checkbox-multiple-blank-fill");
iconList.push("ri-checkbox-multiple-line");
iconList.push("ri-checkbox-multiple-fill");
iconList.push("ri-check-line");
iconList.push("ri-check-fill");
iconList.push("ri-check-double-line");
iconList.push("ri-check-double-fill");
iconList.push("ri-close-line");
iconList.push("ri-close-fill");
iconList.push("ri-add-line");
iconList.push("ri-add-fill");
iconList.push("ri-subtract-line");
iconList.push("ri-subtract-fill");
iconList.push("ri-divide-line");
iconList.push("ri-divide-fill");
iconList.push("ri-arrow-left-up-line");
iconList.push("ri-arrow-left-up-fill");
iconList.push("ri-arrow-up-line");
iconList.push("ri-arrow-up-fill");
iconList.push("ri-arrow-right-up-line");
iconList.push("ri-arrow-right-up-fill");
iconList.push("ri-arrow-right-line");
iconList.push("ri-arrow-right-fill");
iconList.push("ri-arrow-right-down-line");
iconList.push("ri-arrow-right-down-fill");
iconList.push("ri-arrow-down-line");
iconList.push("ri-arrow-down-fill");
iconList.push("ri-arrow-left-down-line");
iconList.push("ri-arrow-left-down-fill");
iconList.push("ri-arrow-left-line");
iconList.push("ri-arrow-left-fill");
iconList.push("ri-arrow-up-circle-line");
iconList.push("ri-arrow-up-circle-fill");
iconList.push("ri-arrow-right-circle-line");
iconList.push("ri-arrow-right-circle-fill");
iconList.push("ri-arrow-down-circle-line");
iconList.push("ri-arrow-down-circle-fill");
// iconList.push("ri-arrow-left-circle-line"); ​iconList.push("ri-arrow-left-circle-fill"); ​iconList.push("ri-arrow-up-s-line"); ​iconList.push("ri-arrow-up-s-fill"); ​
// iconList.push("ri-arrow-down-s-line"); ​iconList.push("ri-arrow-down-s-fill"); ​iconList.push("ri-arrow-right-s-line"); ​iconList.push("ri-arrow-right-s-fill"); ​
// iconList.push("ri-arrow-left-s-line"); ​iconList.push("ri-arrow-left-s-fill"); ​iconList.push("ri-arrow-drop-up-line"); ​iconList.push("ri-arrow-drop-up-fill"); ​
// iconList.push("ri-arrow-drop-right-line"); ​iconList.push("ri-arrow-drop-right-fill"); ​iconList.push("ri-arrow-drop-down-line"); ​iconList.push("ri-arrow-drop-down-fill"); ​
// iconList.push("ri-arrow-drop-left-line"); ​iconList.push("ri-arrow-drop-left-fill"); ​iconList.push("ri-arrow-left-right-line"); ​iconList.push("ri-arrow-left-right-fill"); ​
// iconList.push("ri-arrow-up-down-line"); ​iconList.push("ri-arrow-up-down-fill"); ​iconList.push("ri-arrow-go-back-line"); ​iconList.push("ri-arrow-go-back-fill"); ​
// iconList.push("ri-arrow-go-forward-line"); ​iconList.push("ri-arrow-go-forward-fill"); ​iconList.push("ri-download-line"); ​iconList.push("ri-download-fill"); ​
// iconList.push("ri-upload-line"); ​iconList.push("ri-upload-fill"); ​iconList.push("ri-download-2-line"); ​iconList.push("ri-download-2-fill"); ​iconList.push("ri-upload-2-line"); ​
// iconList.push("ri-upload-2-fill"); ​iconList.push("ri-download-cloud-line"); ​iconList.push("ri-download-cloud-fill"); ​iconList.push("ri-download-cloud-2-line"); ​
// iconList.push("ri-download-cloud-2-fill"); ​iconList.push("ri-upload-cloud-line"); ​iconList.push("ri-upload-cloud-fill"); ​iconList.push("ri-upload-cloud-2-line"); ​
// iconList.push("ri-upload-cloud-2-fill"); ​iconList.push("ri-login-box-line"); ​iconList.push("ri-login-box-fill"); ​iconList.push("ri-logout-box-line"); ​
// iconList.push("ri-logout-box-fill"); ​iconList.push("ri-logout-box-r-line"); ​iconList.push("ri-logout-box-r-fill"); ​iconList.push("ri-login-circle-line"); ​
// iconList.push("ri-login-circle-fill"); ​iconList.push("ri-logout-circle-line"); ​iconList.push("ri-logout-circle-fill"); ​iconList.push("ri-logout-circle-r-line"); ​
// iconList.push("ri-logout-circle-r-fill"); ​iconList.push("ri-refresh-line"); ​iconList.push("ri-refresh-fill"); ​iconList.push("ri-shield-line"); ​iconList.push("ri-shield-fill"); ​
// iconList.push("ri-shield-cross-line"); ​iconList.push("ri-shield-cross-fill"); ​iconList.push("ri-shield-flash-line"); ​iconList.push("ri-shield-flash-fill"); ​
// iconList.push("ri-shield-star-line"); ​iconList.push("ri-shield-star-fill"); ​iconList.push("ri-shield-user-line"); ​iconList.push("ri-shield-user-fill"); ​
// iconList.push("ri-shield-keyhole-line"); ​iconList.push("ri-shield-keyhole-fill"); ​iconList.push("ri-shield-check-line"); ​iconList.push("ri-shield-check-fill"); ​
// iconList.push("ri-delete-back-line"); ​iconList.push("ri-delete-back-fill"); ​iconList.push("ri-delete-back-2-line"); ​iconList.push("ri-delete-back-2-fill"); ​
// iconList.push("ri-delete-bin-line"); ​iconList.push("ri-delete-bin-fill"); ​iconList.push("ri-delete-bin-2-line"); ​iconList.push("ri-delete-bin-2-fill"); ​
// iconList.push("ri-delete-bin-3-line"); ​iconList.push("ri-delete-bin-3-fill"); ​iconList.push("ri-delete-bin-4-line"); ​iconList.push("ri-delete-bin-4-fill"); ​
// iconList.push("ri-delete-bin-5-line"); ​iconList.push("ri-delete-bin-5-fill"); ​iconList.push("ri-delete-bin-6-line"); ​iconList.push("ri-delete-bin-6-fill"); ​
// iconList.push("ri-delete-bin-7-line"); ​iconList.push("ri-delete-bin-7-fill"); ​iconList.push("ri-lock-line"); ​iconList.push("ri-lock-fill"); ​iconList.push("ri-lock-2-line"); ​
// iconList.push("ri-lock-2-fill"); ​iconList.push("ri-lock-password-line"); ​iconList.push("ri-lock-password-fill"); ​iconList.push("ri-lock-unlock-line"); ​
// iconList.push("ri-lock-unlock-fill"); ​iconList.push("ri-eye-line"); ​iconList.push("ri-eye-fill"); ​iconList.push("ri-eye-off-line"); ​iconList.push("ri-eye-off-fill"); ​iconList.push("ri-eye-2-line"); ​
// iconList.push("ri-eye-2-fill"); ​iconList.push("ri-eye-close-line"); ​iconList.push("ri-eye-close-fill"); ​iconList.push("ri-search-line"); ​iconList.push("ri-search-fill"); ​
// iconList.push("ri-search-2-line"); ​iconList.push("ri-search-2-fill"); ​iconList.push("ri-search-eye-line"); ​iconList.push("ri-search-eye-fill"); ​iconList.push("ri-zoom-in-line"); ​
// iconList.push("ri-zoom-in-fill"); ​iconList.push("ri-zoom-out-line"); ​iconList.push("ri-zoom-out-fill"); ​iconList.push("ri-find-replace-line"); ​iconList.push("ri-find-replace-fill"); ​
// iconList.push("ri-share-line"); ​iconList.push("ri-share-fill"); ​iconList.push("ri-share-box-line"); ​iconList.push("ri-share-box-fill"); ​iconList.push("ri-share-circle-line"); ​
// iconList.push("ri-share-circle-fill"); ​iconList.push("ri-share-forward-line"); ​iconList.push("ri-share-forward-fill"); ​iconList.push("ri-share-forward-2-line"); ​
// iconList.push("ri-share-forward-2-fill"); ​iconList.push("ri-share-forward-box-line"); ​iconList.push("ri-share-forward-box-fill"); ​iconList.push("ri-side-bar-line"); ​
// iconList.push("ri-side-bar-fill"); ​iconList.push("ri-time-line"); ​iconList.push("ri-time-fill"); ​iconList.push("ri-timer-line"); ​iconList.push("ri-timer-fill"); ​iconList.push("ri-timer-2-line");
iconList.push("ri-timer-2-fill");
iconList.push("ri-timer-flash-line");
iconList.push("ri-timer-flash-fill");
iconList.push("ri-alarm-line");
iconList.push("ri-alarm-fill");
iconList.push("ri-history-line");
iconList.push("ri-history-fill");
iconList.push("ri-thumb-down-line");
iconList.push("ri-thumb-down-fill");
iconList.push("ri-thumb-up-line");
iconList.push("ri-thumb-up-fill");
iconList.push("ri-alarm-warning-line");
iconList.push("ri-alarm-warning-fill");
iconList.push("ri-notification-badge-line");
iconList.push("ri-notification-badge-fill");
iconList.push("ri-toggle-line");
iconList.push("ri-toggle-fill");
iconList.push("ri-filter-line");
iconList.push("ri-filter-fill");
iconList.push("ri-filter-2-line");
iconList.push("ri-filter-2-fill");
iconList.push("ri-filter-3-line");
iconList.push("ri-filter-3-fill");
iconList.push("ri-filter-off-line");
iconList.push("ri-filter-off-fill");
iconList.push("ri-loader-line");
iconList.push("ri-loader-fill");
iconList.push("ri-loader-2-line");
iconList.push("ri-loader-2-fill");
iconList.push("ri-loader-3-line");
iconList.push("ri-loader-3-fill");
iconList.push("ri-loader-4-line");
iconList.push("ri-loader-4-fill");
iconList.push("ri-loader-5-line");
iconList.push("ri-loader-5-fill");
iconList.push("ri-external-link-line");
iconList.push("ri-external-link-fill");
iconList.push("ri-user-line");
iconList.push("ri-user-fill");
iconList.push("ri-user-2-line");
iconList.push("ri-user-2-fill");
iconList.push("ri-user-3-line");
iconList.push("ri-user-3-fill");
iconList.push("ri-user-4-line");
iconList.push("ri-user-4-fill");
iconList.push("ri-user-5-line");
iconList.push("ri-user-5-fill");
iconList.push("ri-user-6-line");
iconList.push("ri-user-6-fill");
iconList.push("ri-user-smile-line");
iconList.push("ri-user-smile-fill");
iconList.push("ri-account-box-line");
iconList.push("ri-account-box-fill");
iconList.push("ri-account-circle-line");
iconList.push("ri-account-circle-fill");
iconList.push("ri-account-pin-box-line");
iconList.push("ri-account-pin-box-fill");
iconList.push("ri-account-pin-circle-line");
iconList.push("ri-account-pin-circle-fill");
iconList.push("ri-user-add-line");
iconList.push("ri-user-add-fill");
iconList.push("ri-user-follow-line");
iconList.push("ri-user-follow-fill");
iconList.push("ri-user-unfollow-line");
iconList.push("ri-user-unfollow-fill");
iconList.push("ri-user-shared-line");
iconList.push("ri-user-shared-fill");
iconList.push("ri-user-shared-2-line");
iconList.push("ri-user-shared-2-fill");
iconList.push("ri-user-received-line");
iconList.push("ri-user-received-fill");
iconList.push("ri-user-received-2-line");
iconList.push("ri-user-received-2-fill");
iconList.push("ri-user-location-line");
iconList.push("ri-user-location-fill");
iconList.push("ri-user-search-line");
iconList.push("ri-user-search-fill");
iconList.push("ri-user-settings-line");
iconList.push("ri-user-settings-fill");
iconList.push("ri-user-star-line");
iconList.push("ri-user-star-fill");
iconList.push("ri-user-heart-line");
iconList.push("ri-user-heart-fill");
iconList.push("ri-admin-line");
iconList.push("ri-admin-fill");
iconList.push("ri-contacts-line");
iconList.push("ri-contacts-fill");
iconList.push("ri-group-line");
iconList.push("ri-group-fill");
iconList.push("ri-group-2-line");
iconList.push("ri-group-2-fill");
iconList.push("ri-team-line");
iconList.push("ri-team-fill");
iconList.push("ri-user-voice-line");
iconList.push("ri-user-voice-fill");
iconList.push("ri-emotion-line");
iconList.push("ri-emotion-fill");
iconList.push("ri-emotion-2-line");
iconList.push("ri-emotion-2-fill");
iconList.push("ri-emotion-happy-line");
iconList.push("ri-emotion-happy-fill");
iconList.push("ri-emotion-normal-line");
iconList.push("ri-emotion-normal-fill");
iconList.push("ri-emotion-unhappy-line");
iconList.push("ri-emotion-unhappy-fill");
iconList.push("ri-emotion-laugh-line");
iconList.push("ri-emotion-laugh-fill");
iconList.push("ri-emotion-sad-line");
iconList.push("ri-emotion-sad-fill");
iconList.push("ri-skull-line");
iconList.push("ri-skull-fill");
iconList.push("ri-skull-2-line");
iconList.push("ri-skull-2-fill");
iconList.push("ri-men-line");
iconList.push("ri-men-fill");
iconList.push("ri-women-line");
iconList.push("ri-women-fill");
iconList.push("ri-travesti-line");
iconList.push("ri-travesti-fill");
iconList.push("ri-genderless-line");
iconList.push("ri-genderless-fill");
iconList.push("ri-open-arm-line");
iconList.push("ri-open-arm-fill");
iconList.push("ri-body-scan-line");
iconList.push("ri-body-scan-fill");
iconList.push("ri-parent-line");
iconList.push("ri-parent-fill");
iconList.push("ri-robot-line");
iconList.push("ri-robot-fill");
iconList.push("ri-aliens-line");
iconList.push("ri-aliens-fill");
iconList.push("ri-bear-smile-line");
iconList.push("ri-bear-smile-fill");
iconList.push("ri-mickey-line");
iconList.push("ri-mickey-fill");
iconList.push("ri-criminal-line");
iconList.push("ri-criminal-fill");
iconList.push("ri-ghost-line");
iconList.push("ri-ghost-fill");
iconList.push("ri-ghost-2-line");
iconList.push("ri-ghost-2-fill");
iconList.push("ri-ghost-smile-line");
iconList.push("ri-ghost-smile-fill");
iconList.push("ri-star-smile-line");
iconList.push("ri-star-smile-fill");
iconList.push("ri-spy-line");
iconList.push("ri-spy-fill");
iconList.push("ri-sun-line");
iconList.push("ri-sun-fill");
iconList.push("ri-moon-line");
iconList.push("ri-moon-fill");
iconList.push("ri-flashlight-line");
iconList.push("ri-flashlight-fill");
iconList.push("ri-cloudy-line");
iconList.push("ri-cloudy-fill");
iconList.push("ri-cloudy-2-line");
iconList.push("ri-cloudy-2-fill");
iconList.push("ri-mist-line");
iconList.push("ri-mist-fill");
iconList.push("ri-foggy-line");
iconList.push("ri-foggy-fill");
iconList.push("ri-cloud-windy-line");
iconList.push("ri-cloud-windy-fill");
iconList.push("ri-windy-line");
iconList.push("ri-windy-fill");
iconList.push("ri-rainy-line");
iconList.push("ri-rainy-fill");
iconList.push("ri-drizzle-line");
iconList.push("ri-drizzle-fill");
iconList.push("ri-showers-line");
iconList.push("ri-showers-fill");
iconList.push("ri-heavy-showers-line");
iconList.push("ri-heavy-showers-fill");
iconList.push("ri-thunderstorms-line");
iconList.push("ri-thunderstorms-fill");
iconList.push("ri-hail-line");
iconList.push("ri-hail-fill");
iconList.push("ri-snowy-line");
iconList.push("ri-snowy-fill");
iconList.push("ri-sun-cloudy-line");
iconList.push("ri-sun-cloudy-fill");
iconList.push("ri-moon-cloudy-line");
iconList.push("ri-moon-cloudy-fill");
iconList.push("ri-tornado-line");
iconList.push("ri-tornado-fill");
iconList.push("ri-typhoon-line");
iconList.push("ri-typhoon-fill");
iconList.push("ri-haze-line");
iconList.push("ri-haze-fill");
iconList.push("ri-haze-2-line");
iconList.push("ri-haze-2-fill");
iconList.push("ri-sun-foggy-line");
iconList.push("ri-sun-foggy-fill");
iconList.push("ri-moon-foggy-line");
iconList.push("ri-moon-foggy-fill");
iconList.push("ri-moon-clear-line");
iconList.push("ri-moon-clear-fill");
iconList.push("ri-temp-hot-line");
iconList.push("ri-temp-hot-fill");
iconList.push("ri-temp-cold-line");
iconList.push("ri-temp-cold-fill");
iconList.push("ri-celsius-line");
iconList.push("ri-celsius-fill");
iconList.push("ri-fahrenheit-line");
iconList.push("ri-fahrenheit-fill");
iconList.push("ri-fire-line");
iconList.push("ri-fire-fill");
iconList.push("ri-blaze-line");
iconList.push("ri-blaze-fill");
iconList.push("ri-earthquake-line");
iconList.push("ri-earthquake-fill");
iconList.push("ri-flood-line");
iconList.push("ri-flood-fill");
iconList.push("ri-meteor-line");
iconList.push("ri-meteor-fill");
iconList.push("ri-rainbow-line");
iconList.push("ri-rainbow-fill");
iconList.push("ri-basketball-line");
iconList.push("ri-basketball-fill");
iconList.push("ri-bell-line");
iconList.push("ri-bell-fill");
iconList.push("ri-billiards-line");
iconList.push("ri-billiards-fill");
iconList.push("ri-boxing-line");
iconList.push("ri-boxing-fill");
iconList.push("ri-cake-line");
iconList.push("ri-cake-fill");
iconList.push("ri-cake-2-line");
iconList.push("ri-cake-2-fill");
iconList.push("ri-cake-3-line");
iconList.push("ri-cake-3-fill");
iconList.push("ri-door-lock-line");
iconList.push("ri-door-lock-fill");
iconList.push("ri-door-lock-box-line");
iconList.push("ri-door-lock-box-fill");
iconList.push("ri-football-line");
iconList.push("ri-football-fill");
iconList.push("ri-game-line");
iconList.push("ri-game-fill");
iconList.push("ri-handbag-line");
iconList.push("ri-handbag-fill");
iconList.push("ri-key-line");
iconList.push("ri-key-fill");
iconList.push("ri-key-2-line");
iconList.push("ri-key-2-fill");
iconList.push("ri-knife-line");
iconList.push("ri-knife-fill");
iconList.push("ri-knife-blood-line");
iconList.push("ri-knife-blood-fill");
iconList.push("ri-lightbulb-line");
iconList.push("ri-lightbulb-fill");
iconList.push("ri-lightbulb-flash-line");
iconList.push("ri-lightbulb-flash-fill");
iconList.push("ri-outlet-line");
iconList.push("ri-outlet-fill");
iconList.push("ri-outlet-2-line");
iconList.push("ri-outlet-2-fill");
iconList.push("ri-ping-pong-line");
iconList.push("ri-ping-pong-fill");
iconList.push("ri-plug-line");
iconList.push("ri-plug-fill");
iconList.push("ri-plug-2-line");
iconList.push("ri-plug-2-fill");
iconList.push("ri-reserved-line");
iconList.push("ri-reserved-fill");
iconList.push("ri-shirt-line");
iconList.push("ri-shirt-fill");
iconList.push("ri-sword-line");
iconList.push("ri-sword-fill");
iconList.push("ri-t-shirt-line");
iconList.push("ri-t-shirt-fill");
iconList.push("ri-t-shirt-2-line");
iconList.push("ri-t-shirt-2-fill");
iconList.push("ri-t-shirt-air-line");
iconList.push("ri-t-shirt-air-fill");
iconList.push("ri-umbrella-line");
iconList.push("ri-umbrella-fill");
iconList.push("ri-character-recognition-line");
iconList.push("ri-character-recognition-fill");
iconList.push("ri-voice-recognition-line");
iconList.push("ri-voice-recognition-fill");
iconList.push("ri-leaf-line");
iconList.push("ri-leaf-fill");
iconList.push("ri-plant-line");
iconList.push("ri-plant-fill");
iconList.push("ri-seedling-line");
iconList.push("ri-seedling-fill");
iconList.push("ri-recycle-line");
iconList.push("ri-recycle-fill");
iconList.push("ri-scales-line");
iconList.push("ri-scales-fill");
iconList.push("ri-scales-2-line");
iconList.push("ri-scales-2-fill");
iconList.push("ri-scales-3-line");
iconList.push("ri-scales-3-fill");
iconList.push("ri-fridge-line");
iconList.push("ri-fridge-fill");
iconList.push("ri-wheelchair-line");
iconList.push("ri-wheelchair-fill");
iconList.push("ri-cactus-line");
iconList.push("ri-cactus-fill");
iconList.push("ri-door-line");
iconList.push("ri-door-fill");
iconList.push("ri-door-open-line");
iconList.push("ri-door-open-fill");
iconList.push("ri-door-closed-line");
iconList.push("ri-door-closed-fill");


  return iconList;
}
